name: binary

on:
  push:
    # workflow_dispatch:
    tags:
      - "*"

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: git fetch --force --tags

      - uses: actions/setup-go@v4
        with:
          go-version: ">=1.21.0"

      - name: Go Mod
        run: go mod download

      # TODO remove temporary workaround
      - run: bun i --frozen-lockfile
      - run: git reset --hard

      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # AUR_KEY: ${{ secrets.AUR_KEY }}
